### ISSUE TITLE
EDD 3.0 - expiration time should be 23:59

### ISSUE THREAD

**Issue by robincornett** [easydigitaldownloads/edd-discount-code-generator#11]
In EDD 3.0, the default discount expiration time is 23:59, but generated codes are being set to 00:00.

They are correct in 2.10.

**Comment by ashleyfae** [comment]
@LisaCee A good place to put this conversion is in here: https://github.com/easydigitaldownloads/edd-discount-code-generator/blob/release/1.1.1/includes/discount-actions.php#L96

Check if `$code['expiration']` exists, and if so, re-format it to be `Y-m-d 23:59:59`
